services:
  auth-service:
    build:
      context: ./packages/auth-service
      dockerfile: Dockerfile
    ports:
      - "${PORTA}:${PORTA}"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - PORT=${PORTA}
    depends_on:
      - supabase

  blog-service:
    build:
      context: ./packages/blog-service
      dockerfile: Dockerfile
    ports:
      - "${PORTB}:${PORTB}"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - PORT=${PORTB}
    depends_on:
      - supabase

  comment-service:
    build:
      context: ./packages/comment-service
      dockerfile: Dockerfile
    ports:
      - "${PORTC}:${PORTC}"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - PORT=${PORTC}
    depends_on:
      - supabase

  supabase:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=your_postgres_password
    ports:
      - "5432:5432"
